// Generated by Sterling SDK Generator
// Task Manager API v0.2.0

import 'dart:convert';
import 'dart:io';
import 'dart:math';

import 'errors.dart';
import 'models.dart';

/// Log level for SDK output.
enum LogLevel { off, error, warn, info, debug }

LogLevel _parseLogLevel(String? s) {
  switch (s?.toLowerCase()) {
    case 'debug': return LogLevel.debug;
    case 'info': return LogLevel.info;
    case 'warn': return LogLevel.warn;
    case 'error': return LogLevel.error;
    case 'off': return LogLevel.off;
    default: return LogLevel.warn;
  }
}

/// Per-request overrides.
class RequestOptions {
  final Map<String, String>? headers;
  final Duration? timeout;
  const RequestOptions({this.headers, this.timeout});
}

/// Client for Task Manager API.
class TaskmanagerSdkClient {
  final String baseUrl;
  final String? apiKey;
  final Map<String, String> headers;
  final int maxRetries;
  final Duration timeout;
  final LogLevel logLevel;
  final HttpClient _httpClient;

  TaskmanagerSdkClient({
    String? baseUrl,
    String? apiKey,
    this.headers = const {},
    this.maxRetries = 2,
    this.timeout = const Duration(seconds: 30),
    HttpClient? httpClient,
  })  : baseUrl = baseUrl ??
            Platform.environment['VERS_BASE_URL'] ??
            'http://localhost:8080',
        apiKey = apiKey ?? Platform.environment['VERS_API_KEY'],
        logLevel = _parseLogLevel(Platform.environment['VERS_LOG']),
        _httpClient = httpClient ?? HttpClient() {
    _httpClient.connectionTimeout = timeout;
  }

  void _log(LogLevel level, String message) {
    if (logLevel.index >= level.index) {
      stderr.writeln('[taskmanager-sdk] $message');
    }
  }

  static final _retryableCodes = {408, 409, 429};

  bool _isRetryable(int code) => code >= 500 || _retryableCodes.contains(code);

  Duration _retryDelay(int attempt) {
    final baseMs = 500.0 * pow(2, attempt);
    final jitter = Random().nextDouble() * baseMs * 0.25;
    return Duration(milliseconds: (baseMs + jitter).round());
  }

  String _generateIdempotencyKey() {
    final rng = Random.secure();
    final bytes = List<int>.generate(16, (_) => rng.nextInt(256));
    return bytes.map((b) => b.toRadixString(16).padLeft(2, '0')).join();
  }

  Future<Map<String, dynamic>> _doRequest(
    String method,
    String path, {
    Object? body,
    RequestOptions? options,
  }) async {
    _log(LogLevel.debug, 'request: $method $path');
    final idempotencyKey = ['POST', 'PUT', 'PATCH', 'DELETE'].contains(method)
        ? _generateIdempotencyKey()
        : null;

    Object? lastError;
    for (var attempt = 0; attempt <= maxRetries; attempt++) {
      if (attempt > 0) {
        _log(LogLevel.info, 'retry attempt $attempt/$maxRetries for $method $path');
        await Future.delayed(_retryDelay(attempt - 1));
      }

      HttpClientRequest request;
      try {
        final uri = Uri.parse('$baseUrl$path');
        request = await _httpClient.openUrl(method, uri);
      } catch (e) {
        _log(LogLevel.error, 'connection error: $method $path - $e');
        lastError = APIConnectionError(message: e.toString());
        if (attempt == maxRetries) throw lastError as APIConnectionError;
        continue;
      }

      request.headers.set('Content-Type', 'application/json');
      request.headers.set('User-Agent',
          'taskmanager-sdk/0.2.0 dart/${Platform.version.split(' ').first}');
      if (apiKey != null && apiKey!.isNotEmpty) {
        request.headers.set('Authorization', 'Bearer $apiKey');
      }
      if (idempotencyKey != null) {
        request.headers.set('X-Idempotency-Key', idempotencyKey);
      }
      headers.forEach((k, v) => request.headers.set(k, v));
      options?.headers?.forEach((k, v) => request.headers.set(k, v));

      if (body != null) {
        request.write(jsonEncode(body));
      }

      HttpClientResponse response;
      try {
        response = await request.close();
      } catch (e) {
        _log(LogLevel.error, 'connection error: $method $path - $e');
        lastError = APIConnectionError(message: e.toString());
        if (attempt == maxRetries) throw lastError as APIConnectionError;
        continue;
      }

      _log(LogLevel.debug, 'response: ${response.statusCode} for $method $path');

      if (_isRetryable(response.statusCode) && attempt < maxRetries) {
        await response.drain();
        lastError = Exception('HTTP ${response.statusCode}');
        continue;
      }

      final bodyStr = await response.transform(utf8.decoder).join();

      if (response.statusCode < 200 || response.statusCode >= 300) {
        final responseHeaders = <String, String>{};
        response.headers.forEach((name, values) {
          responseHeaders[name] = values.join(', ');
        });
        _log(LogLevel.error,
            'API error: ${response.statusCode} $method $path');
        throw APIError.generate(
          response.statusCode,
          bodyStr,
          responseHeaders,
        );
      }

      if (bodyStr.isEmpty) return <String, dynamic>{};

      final decoded = jsonDecode(bodyStr);
      if (decoded is Map<String, dynamic>) return decoded;
      if (decoded is List) return {'data': decoded};
      return {'value': decoded};
    }
    throw lastError ?? Exception('Request failed');
  }

  /// List all tasks
  Future<Map<String, dynamic>> listTasks(String? status, int? limit, [RequestOptions? options]) async {
    const reqPath = '/api/tasks';
    final qp = <String, String>{};
    if (status != null) qp['status'] = status.toString();
    if (limit != null) qp['limit'] = limit.toString();
    final queryString = qp.isNotEmpty
        ? '?${qp.entries.map((e) => '${Uri.encodeComponent(e.key)}=${Uri.encodeComponent(e.value)}').join('&')}'
        : '';
    return _doRequest('GET', '$reqPath$queryString', options: options);
  }

  /// Create a new task
  Future<Map<String, dynamic>> createTask(Map<String, dynamic> body, [RequestOptions? options]) async {
    const reqPath = '/api/tasks';
    return _doRequest('POST', reqPath, body: body, options: options);
  }

  /// Get a task by ID
  Future<Map<String, dynamic>> getTask(String task_id, [RequestOptions? options]) async {
    final reqPath = '/api/tasks/$task_id';
    return _doRequest('GET', reqPath, options: options);
  }

  /// Delete a task
  Future<Map<String, dynamic>> deleteTask(String task_id, [RequestOptions? options]) async {
    final reqPath = '/api/tasks/$task_id';
    return _doRequest('DELETE', reqPath, options: options);
  }

  /// Update a task
  Future<Map<String, dynamic>> updateTask(String task_id, Map<String, dynamic> body, [RequestOptions? options]) async {
    final reqPath = '/api/tasks/$task_id';
    return _doRequest('PATCH', reqPath, body: body, options: options);
  }

  /// Mark a task as done
  Future<Map<String, dynamic>> completeTask(String task_id, Map<String, dynamic> body, [RequestOptions? options]) async {
    final reqPath = '/api/tasks/$task_id/complete';
    return _doRequest('POST', reqPath, body: body, options: options);
  }

  /// Close the HTTP client and free resources.
  void close() {
    _httpClient.close();
  }
}
