// Generated by Sterling SDK Generator
// Task Manager API v0.2.0

import 'dart:convert';

/// Base class for SDK errors.
class SDKError implements Exception {
  final String message;
  const SDKError({required this.message});

  @override
  String toString() => message;
}

/// Error thrown when a connection to the API cannot be established.
class APIConnectionError extends SDKError {
  const APIConnectionError({required super.message});
}

/// Error thrown when the connection times out.
class APIConnectionTimeoutError extends APIConnectionError {
  const APIConnectionTimeoutError({required super.message});
}

/// Base class for API errors with an HTTP status code.
class APIError extends SDKError {
  final int status;
  final String body;
  final Map<String, String> headers;

  const APIError({
    required this.status,
    required this.body,
    required super.message,
    this.headers = const {},
  });

  /// Extract the human-readable error message from the response body.
  /// Looks for an "error" or "message" field in the JSON body, or falls
  /// back to the raw body text.
  String get errorMessage {
    try {
      final decoded = jsonDecode(body);
      if (decoded is Map<String, dynamic>) {
        final err = decoded['error'];
        if (err is String) return err;
        final msg = decoded['message'];
        if (msg is String) return msg;
      }
    } catch (_) {}
    return body;
  }

  @override
  String toString() => '$status $body';

  /// Generate a typed error based on the HTTP status code.
  static APIError generate(
    int status,
    String body,
    Map<String, String> headers,
  ) {
    final message = '$status $body';
    switch (status) {
      case 400:
        return BadRequestError(status: status, body: body, message: message, headers: headers);
      case 401:
        return AuthenticationError(status: status, body: body, message: message, headers: headers);
      case 403:
        return PermissionDeniedError(status: status, body: body, message: message, headers: headers);
      case 404:
        return NotFoundError(status: status, body: body, message: message, headers: headers);
      case 409:
        return ConflictError(status: status, body: body, message: message, headers: headers);
      case 422:
        return UnprocessableEntityError(status: status, body: body, message: message, headers: headers);
      case 429:
        return RateLimitError(status: status, body: body, message: message, headers: headers);
      default:
        if (status >= 500) {
          return InternalServerError(status: status, body: body, message: message, headers: headers);
        }
        return APIError(status: status, body: body, message: message, headers: headers);
    }
  }
}

/// 400 Bad Request.
class BadRequestError extends APIError {
  const BadRequestError({required super.status, required super.body, required super.message, super.headers});
}

/// 401 Unauthorized.
class AuthenticationError extends APIError {
  const AuthenticationError({required super.status, required super.body, required super.message, super.headers});
}

/// 403 Forbidden.
class PermissionDeniedError extends APIError {
  const PermissionDeniedError({required super.status, required super.body, required super.message, super.headers});
}

/// 404 Not Found.
class NotFoundError extends APIError {
  const NotFoundError({required super.status, required super.body, required super.message, super.headers});
}

/// 409 Conflict.
class ConflictError extends APIError {
  const ConflictError({required super.status, required super.body, required super.message, super.headers});
}

/// 422 Unprocessable Entity.
class UnprocessableEntityError extends APIError {
  const UnprocessableEntityError({required super.status, required super.body, required super.message, super.headers});
}

/// 429 Too Many Requests.
class RateLimitError extends APIError {
  const RateLimitError({required super.status, required super.body, required super.message, super.headers});
}

/// 5xx Internal Server Error.
class InternalServerError extends APIError {
  const InternalServerError({required super.status, required super.body, required super.message, super.headers});
}
