// Generated by Sterling SDK Generator
// Task Manager API v0.2.0

/// 
class Task {
  final String id;
  final String title;
  final String? description;
  final String status;
  final int priority;
  final String created_at;
  final String updated_at;
  final String? due_date;

  const Task({
    required this.id,
    required this.title,
    this.description,
    required this.status,
    required this.priority,
    required this.created_at,
    required this.updated_at,
    this.due_date,
  });

  factory Task.fromJson(Map<String, dynamic> json) {
    return Task(
      id: json['id'],
      title: json['title'],
      description: json['description'],
      status: json['status'],
      priority: json['priority'],
      created_at: json['created_at'],
      updated_at: json['updated_at'],
      due_date: json['due_date'],
    );
  }

  Map<String, dynamic> toJson() => {
    'id': id,
    'title': title,
    'description': description,
    'status': status,
    'priority': priority,
    'created_at': created_at,
    'updated_at': updated_at,
    'due_date': due_date,
  };
}

/// 
class TaskListResponse {
  final List<Task> tasks;
  final int total;

  const TaskListResponse({
    required this.tasks,
    required this.total,
  });

  factory TaskListResponse.fromJson(Map<String, dynamic> json) {
    return TaskListResponse(
      tasks: json['tasks'],
      total: json['total'],
    );
  }

  Map<String, dynamic> toJson() => {
    'tasks': tasks,
    'total': total,
  };
}

/// 
class ErrorResponse {
  /// Human-readable error message
  final String error;
  /// Always false for errors
  final bool success;

  const ErrorResponse({
    required this.error,
    required this.success,
  });

  factory ErrorResponse.fromJson(Map<String, dynamic> json) {
    return ErrorResponse(
      error: json['error'],
      success: json['success'],
    );
  }

  Map<String, dynamic> toJson() => {
    'error': error,
    'success': success,
  };
}

/// 
class CreateTaskRequest {
  /// Task title (required)
  final String title;
  /// Optional description
  final String? description;
  /// Priority (0 = default)
  final int? priority;
  final String? due_date;

  const CreateTaskRequest({
    required this.title,
    this.description,
    this.priority,
    this.due_date,
  });

  factory CreateTaskRequest.fromJson(Map<String, dynamic> json) {
    return CreateTaskRequest(
      title: json['title'],
      description: json['description'],
      priority: json['priority'],
      due_date: json['due_date'],
    );
  }

  Map<String, dynamic> toJson() => {
    'title': title,
    'description': description,
    'priority': priority,
    'due_date': due_date,
  };
}

/// 
class UpdateTaskRequest {
  final String? title;
  final String? description;
  final String? status;
  final int? priority;
  final String? due_date;

  const UpdateTaskRequest({
    this.title,
    this.description,
    this.status,
    this.priority,
    this.due_date,
  });

  factory UpdateTaskRequest.fromJson(Map<String, dynamic> json) {
    return UpdateTaskRequest(
      title: json['title'],
      description: json['description'],
      status: json['status'],
      priority: json['priority'],
      due_date: json['due_date'],
    );
  }

  Map<String, dynamic> toJson() => {
    'title': title,
    'description': description,
    'status': status,
    'priority': priority,
    'due_date': due_date,
  };
}

